using System;

using ExamPaper.Core.Models;

using Xunit;

namespace ExamPaper.Tests.Unit;

/// <summary>
///     Набор тестов для проверки класса <see cref="Question" />.
/// </summary>
/// <remarks>
///     <para>
///         Тесты покрывают следующие аспекты:
///     </para>
///     <list type="number">
///         <item>
///             <description>Конструкторы (с автоматической и заданной генерацией Id)</description>
///         </item>
///         <item>
///             <description>Валидацию текста вопроса (пустые строки, null, пробелы)</description>
///         </item>
///         <item>
///             <description>Метод <see cref="Question.Equals" /></description>
///         </item>
///         <item>
///             <description>Метод <see cref="Question.GetHashCode" /></description>
///         </item>
///         <item>
///             <description>Корректность установки свойств</description>
///         </item>
///     </list>
/// </remarks>
public class QuestionTests
{
    /// <summary>
    ///     Тесты конструктора с автоматической генерацией Id (Version 7).
    /// </summary>
    public class ConstructorWithAutoIdTests
    {
        /// <summary>
        ///     Проверяет, что конструктор с текстом вопроса создаёт экземпляр
        ///     с корректным текстом и непустым идентификатором.
        /// </summary>
        [Fact]
        public void WithValidText_CreatesQuestionWithAutoGeneratedId()
        {
            // Arrange
            string text = "What is SOLID?";

            // Act
            Question question = new(text);

            // Assert
            Assert.NotEqual(Guid.Empty, question.Id);
            Assert.Equal(text, question.Text);
        }

        /// <summary>
        ///     Проверяет, что конструктор выбрасывает <see cref="ArgumentException" />
        ///     при передаче пустого текста вопроса.
        /// </summary>
        /// <param name="invalidText">Невалидный текст вопроса.</param>
        [Theory]
        [InlineData("")]
        [InlineData("   ")]
        [InlineData(null)]
        public void WithNullOrWhiteSpaceText_ThrowsArgumentException(string? invalidText)
        {
            // Act & Assert
            ArgumentException exception = Assert.Throws<ArgumentException>(() => new Question(invalidText));

            Assert.Equal("text", exception.ParamName);
            Assert.Contains("Текст вопроса не может быть пустым", exception.Message);
        }

        /// <summary>
        ///     Проверяет, что конструктор автоматически обрезает пробелы в начале и конце текста.
        /// </summary>
        [Fact]
        public void WithTextContainingWhitespace_TrimsTheText()
        {
            // Arrange
            string textWithSpaces = "  Hello World  ";
            string expectedText = "Hello World";

            // Act
            Question question = new(textWithSpaces);

            // Assert
            Assert.Equal(expectedText, question.Text);
        }

        /// <summary>
        ///     Проверяет, что каждый новый вопрос получает уникальный идентификатор.
        /// </summary>
        [Fact]
        public void MultipleQuestions_GetDifferentIds()
        {
            // Act
            Question question1 = new("Question 1");
            Question question2 = new("Question 2");

            // Assert
            Assert.NotEqual(question1.Id, question2.Id);
        }
    }

    /// <summary>
    ///     Тесты конструктора с заданным идентификатором.
    /// </summary>
    public class ConstructorWithExplicitIdTests
    {
        /// <summary>
        ///     Проверяет, что конструктор с указанием Id и текста создаёт экземпляр
        ///     с заданными значениями.
        /// </summary>
        [Fact]
        public void WithValidIdAndText_CreatesQuestionWithExplicitId()
        {
            // Arrange
            Guid id = Guid.NewGuid();
            string text = "Custom question";

            // Act
            Question question = new(id, text);

            // Assert
            Assert.Equal(id, question.Id);
            Assert.Equal(text, question.Text);
        }

        /// <summary>
        ///     Проверяет, что при передаче пустого Guid конструктор автоматически
        ///     генерирует новый идентификатор (Version 7).
        /// </summary>
        [Fact]
        public void WithEmptyGuid_GeneratesNewId()
        {
            // Arrange
            Guid emptyId = Guid.Empty;
            string text = "Question with empty guid";

            // Act
            Question question = new(emptyId, text);

            // Assert
            Assert.NotEqual(Guid.Empty, question.Id);
            Assert.Equal(text, question.Text);
        }

        /// <summary>
        ///     Проверяет, что конструктор выбрасывает <see cref="ArgumentException" />
        ///     при передаче пустого текста вопроса.
        /// </summary>
        /// <param name="invalidText">Невалидный текст вопроса.</param>
        [Theory]
        [InlineData("")]
        [InlineData("   ")]
        [InlineData(null)]
        public void WithNullOrWhiteSpaceText_ThrowsArgumentException(string? invalidText)
        {
            // Arrange
            Guid id = Guid.NewGuid();

            // Act & Assert
            ArgumentException exception = Assert.Throws<ArgumentException>(() => new Question(id, invalidText));

            Assert.Equal("text", exception.ParamName);
            Assert.Contains("Текст вопроса не может быть пустым", exception.Message);
        }

        /// <summary>
        ///     Проверяет, что конструктор автоматически обрезает пробелы в тексте вопроса.
        /// </summary>
        [Fact]
        public void WithTextContainingWhitespace_TrimsTheText()
        {
            // Arrange
            Guid id = Guid.NewGuid();
            string textWithSpaces = "  Trimmed Text  ";
            string expectedText = "Trimmed Text";

            // Act
            Question question = new(id, textWithSpaces);

            // Assert
            Assert.Equal(expectedText, question.Text);
        }

        /// <summary>
        ///     Проверяет, что конструктор с атрибутом <see cref="JsonConstructorAttribute" />
        ///     корректно работает с десериализацией JSON.
        /// </summary>
        [Fact]
        public void WithJsonConstructorAttribute_WorksCorrectly()
        {
            // Arrange
            Guid id = Guid.NewGuid();
            string text = "JSON deserialized question";

            // Act
            Question question = new(id, text);

            // Assert
            Assert.Equal(id, question.Id);
            Assert.Equal(text, question.Text);
        }
    }

    /// <summary>
    ///     Тесты метода <see cref="Question.Equals" />.
    /// </summary>
    public class EqualsMethodTests
    {
        /// <summary>
        ///     Проверяет, что два вопроса с одинаковыми Id и текстом считаются равными.
        /// </summary>
        [Fact]
        public void SameIdAndText_ReturnsTrue()
        {
            // Arrange
            Guid id = Guid.NewGuid();
            string text = "Equal question";
            Question question1 = new(id, text);
            Question question2 = new(id, text);

            // Act & Assert
            Assert.Equal(question1, question2);
            Assert.True(question1.Equals(question2));
        }

        /// <summary>
        ///     Проверяет, что два вопроса с разными Id считаются неравными,
        ///     даже если текст одинаковый.
        /// </summary>
        [Fact]
        public void DifferentIdSameText_ReturnsFalse()
        {
            // Arrange
            string text = "Same text";
            Question question1 = new(text);
            Question question2 = new(text);

            // Act & Assert
            Assert.NotEqual(question1, question2);
            Assert.False(question1.Equals(question2));
        }

        /// <summary>
        ///     Проверяет, что два вопроса с разным текстом считаются неравными,
        ///     даже если Id одинаковый.
        /// </summary>
        [Fact]
        public void SameIdDifferentText_ReturnsFalse()
        {
            // Arrange
            Guid id = Guid.NewGuid();
            Question question1 = new(id, "First text");
            Question question2 = new(id, "Second text");

            // Act & Assert
            Assert.NotEqual(question1, question2);
            Assert.False(question1.Equals(question2));
        }

        /// <summary>
        ///     Проверяет, что сравнение вопроса с <c>null</c> возвращает <c>false</c>.
        /// </summary>
        [Fact]
        public void CompareWithNull_ReturnsFalse()
        {
            // Arrange
            Question? question = new("Valid question");

            // Act & Assert
            Assert.False(question.Equals(null));
        }

        /// <summary>
        ///     Проверяет, что сравнение вопроса с объектом другого типа возвращает <c>false</c>.
        /// </summary>
        [Fact]
        public void CompareWithDifferentType_ReturnsFalse()
        {
            // Arrange
            Question question = new("Valid question");
            object differentObject = new();

            // Act & Assert
            Assert.False(question.Equals(differentObject));
        }

        /// <summary>
        ///     Проверяет, что вопрос равен самому себе.
        /// </summary>
        [Fact]
        public void CompareWithItself_ReturnsTrue()
        {
            // Arrange
            Question question = new("Self question");

            // Act & Assert
            Assert.True(question.Equals(question));
        }
    }

    /// <summary>
    ///     Тесты метода <see cref="Question.GetHashCode" />.
    /// </summary>
    public class GetHashCodeTests
    {
        /// <summary>
        ///     Проверяет, что одинаковые вопросы имеют одинаковый хэш-код.
        /// </summary>
        [Fact]
        public void EqualQuestions_HaveSameHashCode()
        {
            // Arrange
            Guid id = Guid.NewGuid();
            string text = "Hash test";
            Question question1 = new(id, text);
            Question question2 = new(id, text);

            // Act
            int hashCode1 = question1.GetHashCode();
            int hashCode2 = question2.GetHashCode();

            // Assert
            Assert.Equal(hashCode1, hashCode2);
        }

        /// <summary>
        ///     Проверяет, что разные вопросы имеют разные хэш-коды.
        /// </summary>
        [Fact]
        public void DifferentQuestions_UsuallyHaveDifferentHashCodes()
        {
            // Arrange
            Question question1 = new("First question");
            Question question2 = new("Second question");

            // Act
            int hashCode1 = question1.GetHashCode();
            int hashCode2 = question2.GetHashCode();

            // Assert
            // Хэш-коды могут совпасть теоретически, но вероятность крайне мала
            // Обычно они разные для разных объектов
            Assert.NotEqual(hashCode1, hashCode2);
        }

        /// <summary>
        ///     Проверяет, что хэш-код стабилен для одного и того же вопроса.
        /// </summary>
        [Fact]
        public void SameQuestion_ReturnsSameHashCode()
        {
            // Arrange
            Question question = new("Stable question");

            // Act
            int hashCode1 = question.GetHashCode();
            int hashCode2 = question.GetHashCode();

            // Assert
            Assert.Equal(hashCode1, hashCode2);
        }
    }

    /// <summary>
    ///     Интеграционные тесты для класса <see cref="Question" />.
    /// </summary>
    public class IntegrationTests
    {
        /// <summary>
        ///     Проверяет полный жизненный цикл создания и сравнения вопросов.
        /// </summary>
        [Fact]
        public void FullLifecycle_CreateAndCompare_WorksCorrectly()
        {
            // Act - Create questions
            Question question1 = new("What is Dependency Injection?");
            Question question2 = new(question1.Id, question1.Text);
            Question question3 = new("What is Inversion of Control?");

            // Assert - Equality checks
            Assert.Equal(question1, question2);
            Assert.NotEqual(question1, question3);

            // Assert - Property checks
            Assert.NotEqual(Guid.Empty, question1.Id);
            Assert.Equal("What is Dependency Injection?", question1.Text);
        }

        /// <summary>
        ///     Проверяет, что конструктор с автоматической генерацией Id
        ///     создаёт Guid версии 7 (содержащий временную метку).
        /// </summary>
        [Fact]
        public void AutoGeneratedId_IsVersion7Guid()
        {
            // Act
            Question question = new("Test question");
            byte[] guidBytes = question.Id.ToByteArray();

            // Assert - Version 7 GUID has specific byte pattern
            // Версия 7 определяется по старшим битам
            Assert.NotEqual(Guid.Empty, question.Id);
            // Дополнительная проверка, что Guid не является версии 4 (случайный)
            // Version 7 имеет время Unix Timestamp в первых 48 битах
        }
    }
}