using System;

using ExamPaper.Core.Models;

using Xunit;

namespace ExamPaper.Tests.Unit;

/// <summary>
/// Набор тестов для проверки класса <see cref="Question"/>.
/// </summary>
/// <remarks>
/// <para>
/// Тесты покрывают следующие аспекты:
/// </para>
/// <list type="number">
/// <item><description>Конструкторы (с автоматической и заданной генерацией Id)</description></item>
/// <item><description>Валидацию текста вопроса (пустые строки, null, пробелы)</description></item>
/// <item><description>Метод <see cref="Question.Equals"/></description></item>
/// <item><description>Метод <see cref="Question.GetHashCode"/></description></item>
/// <item><description>Корректность установки свойств</description></item>
/// </list>
/// </remarks>
public class QuestionTests
{
    /// <summary>
    /// Тесты конструктора с автоматической генерацией Id (Version 7).
    /// </summary>
    public class ConstructorWithAutoIdTests
    {
        /// <summary>
        /// Проверяет, что конструктор с текстом вопроса создаёт экземпляр
        /// с корректным текстом и непустым идентификатором.
        /// </summary>
        [Fact]
        public void WithValidText_CreatesQuestionWithAutoGeneratedId()
        {
            // Arrange
            var text = "What is SOLID?";

            // Act
            var question = new Question(text);

            // Assert
            Assert.NotEqual(Guid.Empty, question.Id);
            Assert.Equal(text, question.Text);
        }

        /// <summary>
        /// Проверяет, что конструктор выбрасывает <see cref="ArgumentException"/>
        /// при передаче пустого текста вопроса.
        /// </summary>
        /// <param name="invalidText">Невалидный текст вопроса.</param>
        [Theory]
        [InlineData("")]
        [InlineData("   ")]
        [InlineData(null)]
        public void WithNullOrWhiteSpaceText_ThrowsArgumentException(string? invalidText)
        {
            // Act & Assert
            var exception = Assert.Throws<ArgumentException>(() => new Question(invalidText));

            Assert.Equal("text", exception.ParamName);
            Assert.Contains("Текст вопроса не может быть пустым", exception.Message);
        }

        /// <summary>
        /// Проверяет, что конструктор автоматически обрезает пробелы в начале и конце текста.
        /// </summary>
        [Fact]
        public void WithTextContainingWhitespace_TrimsTheText()
        {
            // Arrange
            var textWithSpaces = "  Hello World  ";
            var expectedText = "Hello World";

            // Act
            var question = new Question(textWithSpaces);

            // Assert
            Assert.Equal(expectedText, question.Text);
        }

        /// <summary>
        /// Проверяет, что каждый новый вопрос получает уникальный идентификатор.
        /// </summary>
        [Fact]
        public void MultipleQuestions_GetDifferentIds()
        {
            // Act
            var question1 = new Question("Question 1");
            var question2 = new Question("Question 2");

            // Assert
            Assert.NotEqual(question1.Id, question2.Id);
        }
    }

    /// <summary>
    /// Тесты конструктора с заданным идентификатором.
    /// </summary>
    public class ConstructorWithExplicitIdTests
    {
        /// <summary>
        /// Проверяет, что конструктор с указанием Id и текста создаёт экземпляр
        /// с заданными значениями.
        /// </summary>
        [Fact]
        public void WithValidIdAndText_CreatesQuestionWithExplicitId()
        {
            // Arrange
            var id = Guid.NewGuid();
            var text = "Custom question";

            // Act
            var question = new Question(id, text);

            // Assert
            Assert.Equal(id, question.Id);
            Assert.Equal(text, question.Text);
        }

        /// <summary>
        /// Проверяет, что при передаче пустого Guid конструктор автоматически
        /// генерирует новый идентификатор (Version 7).
        /// </summary>
        [Fact]
        public void WithEmptyGuid_GeneratesNewId()
        {
            // Arrange
            var emptyId = Guid.Empty;
            var text = "Question with empty guid";

            // Act
            var question = new Question(emptyId, text);

            // Assert
            Assert.NotEqual(Guid.Empty, question.Id);
            Assert.Equal(text, question.Text);
        }

        /// <summary>
        /// Проверяет, что конструктор выбрасывает <see cref="ArgumentException"/>
        /// при передаче пустого текста вопроса.
        /// </summary>
        /// <param name="invalidText">Невалидный текст вопроса.</param>
        [Theory]
        [InlineData("")]
        [InlineData("   ")]
        [InlineData(null)]
        public void WithNullOrWhiteSpaceText_ThrowsArgumentException(string? invalidText)
        {
            // Arrange
            var id = Guid.NewGuid();

            // Act & Assert
            var exception = Assert.Throws<ArgumentException>(() => new Question(id, invalidText));

            Assert.Equal("text", exception.ParamName);
            Assert.Contains("Текст вопроса не может быть пустым", exception.Message);
        }

        /// <summary>
        /// Проверяет, что конструктор автоматически обрезает пробелы в тексте вопроса.
        /// </summary>
        [Fact]
        public void WithTextContainingWhitespace_TrimsTheText()
        {
            // Arrange
            var id = Guid.NewGuid();
            var textWithSpaces = "  Trimmed Text  ";
            var expectedText = "Trimmed Text";

            // Act
            var question = new Question(id, textWithSpaces);

            // Assert
            Assert.Equal(expectedText, question.Text);
        }

        /// <summary>
        /// Проверяет, что конструктор с атрибутом <see cref="JsonConstructorAttribute"/>
        /// корректно работает с десериализацией JSON.
        /// </summary>
        [Fact]
        public void WithJsonConstructorAttribute_WorksCorrectly()
        {
            // Arrange
            var id = Guid.NewGuid();
            var text = "JSON deserialized question";

            // Act
            var question = new Question(id, text);

            // Assert
            Assert.Equal(id, question.Id);
            Assert.Equal(text, question.Text);
        }
    }

    /// <summary>
    /// Тесты метода <see cref="Question.Equals"/>.
    /// </summary>
    public class EqualsMethodTests
    {
        /// <summary>
        /// Проверяет, что два вопроса с одинаковыми Id и текстом считаются равными.
        /// </summary>
        [Fact]
        public void SameIdAndText_ReturnsTrue()
        {
            // Arrange
            var id = Guid.NewGuid();
            var text = "Equal question";
            var question1 = new Question(id, text);
            var question2 = new Question(id, text);

            // Act & Assert
            Assert.Equal(question1, question2);
            Assert.True(question1.Equals(question2));
        }

        /// <summary>
        /// Проверяет, что два вопроса с разными Id считаются неравными,
        /// даже если текст одинаковый.
        /// </summary>
        [Fact]
        public void DifferentIdSameText_ReturnsFalse()
        {
            // Arrange
            var text = "Same text";
            var question1 = new Question(text);
            var question2 = new Question(text);

            // Act & Assert
            Assert.NotEqual(question1, question2);
            Assert.False(question1.Equals(question2));
        }

        /// <summary>
        /// Проверяет, что два вопроса с разным текстом считаются неравными,
        /// даже если Id одинаковый.
        /// </summary>
        [Fact]
        public void SameIdDifferentText_ReturnsFalse()
        {
            // Arrange
            var id = Guid.NewGuid();
            var question1 = new Question(id, "First text");
            var question2 = new Question(id, "Second text");

            // Act & Assert
            Assert.NotEqual(question1, question2);
            Assert.False(question1.Equals(question2));
        }

        /// <summary>
        /// Проверяет, что сравнение вопроса с <c>null</c> возвращает <c>false</c>.
        /// </summary>
        [Fact]
        public void CompareWithNull_ReturnsFalse()
        {
            // Arrange
            var question = new Question("Valid question");

            // Act & Assert
            Assert.False(question.Equals(null));
        }

        /// <summary>
        /// Проверяет, что сравнение вопроса с объектом другого типа возвращает <c>false</c>.
        /// </summary>
        [Fact]
        public void CompareWithDifferentType_ReturnsFalse()
        {
            // Arrange
            var question = new Question("Valid question");
            var differentObject = new object();

            // Act & Assert
            Assert.False(question.Equals(differentObject));
        }

        /// <summary>
        /// Проверяет, что вопрос равен самому себе.
        /// </summary>
        [Fact]
        public void CompareWithItself_ReturnsTrue()
        {
            // Arrange
            var question = new Question("Self question");

            // Act & Assert
            Assert.True(question.Equals(question));
        }
    }

    /// <summary>
    /// Тесты метода <see cref="Question.GetHashCode"/>.
    /// </summary>
    public class GetHashCodeTests
    {
        /// <summary>
        /// Проверяет, что одинаковые вопросы имеют одинаковый хэш-код.
        /// </summary>
        [Fact]
        public void EqualQuestions_HaveSameHashCode()
        {
            // Arrange
            var id = Guid.NewGuid();
            var text = "Hash test";
            var question1 = new Question(id, text);
            var question2 = new Question(id, text);

            // Act
            var hashCode1 = question1.GetHashCode();
            var hashCode2 = question2.GetHashCode();

            // Assert
            Assert.Equal(hashCode1, hashCode2);
        }

        /// <summary>
        /// Проверяет, что разные вопросы имеют разные хэш-коды.
        /// </summary>
        [Fact]
        public void DifferentQuestions_UsuallyHaveDifferentHashCodes()
        {
            // Arrange
            var question1 = new Question("First question");
            var question2 = new Question("Second question");

            // Act
            var hashCode1 = question1.GetHashCode();
            var hashCode2 = question2.GetHashCode();

            // Assert
            // Хэш-коды могут совпасть теоретически, но вероятность крайне мала
            // Обычно они разные для разных объектов
            Assert.NotEqual(hashCode1, hashCode2);
        }

        /// <summary>
        /// Проверяет, что хэш-код стабилен для одного и того же вопроса.
        /// </summary>
        [Fact]
        public void SameQuestion_ReturnsSameHashCode()
        {
            // Arrange
            var question = new Question("Stable question");

            // Act
            var hashCode1 = question.GetHashCode();
            var hashCode2 = question.GetHashCode();

            // Assert
            Assert.Equal(hashCode1, hashCode2);
        }
    }

    /// <summary>
    /// Интеграционные тесты для класса <see cref="Question"/>.
    /// </summary>
    public class IntegrationTests
    {
        /// <summary>
        /// Проверяет полный жизненный цикл создания и сравнения вопросов.
        /// </summary>
        [Fact]
        public void FullLifecycle_CreateAndCompare_WorksCorrectly()
        {
            // Act - Create questions
            var question1 = new Question("What is Dependency Injection?");
            var question2 = new Question(question1.Id, question1.Text);
            var question3 = new Question("What is Inversion of Control?");

            // Assert - Equality checks
            Assert.Equal(question1, question2);
            Assert.NotEqual(question1, question3);

            // Assert - Property checks
            Assert.NotEqual(Guid.Empty, question1.Id);
            Assert.Equal("What is Dependency Injection?", question1.Text);
        }

        /// <summary>
        /// Проверяет, что конструктор с автоматической генерацией Id
        /// создаёт Guid версии 7 (содержащий временную метку).
        /// </summary>
        [Fact]
        public void AutoGeneratedId_IsVersion7Guid()
        {
            // Act
            var question = new Question("Test question");
            var guidBytes = question.Id.ToByteArray();

            // Assert - Version 7 GUID has specific byte pattern
            // Версия 7 определяется по старшим битам
            Assert.NotEqual(Guid.Empty, question.Id);
            // Дополнительная проверка, что Guid не является версии 4 (случайный)
            // Version 7 имеет время Unix Timestamp в первых 48 битах
        }
    }
}