name: dotnet test

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop
        
env:
  SLN: back/ExamPaper.slnx

jobs:
  check-format:
    runs-on: ubuntu-latest
    concurrency:
      group: format-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Setup environment
        uses: ./.github/actions/setup-dotnet-env
        with:
          restore: 'true'

      - name: Verify formatting
        run: dotnet format $SLN --verify-no-changes --no-restore

  test:
    needs: check-format
    runs-on: ubuntu-latest
    concurrency:
      group: test-${{ github.ref }}
      cancel-in-progress: true
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Setup environment
        uses: ./.github/actions/setup-dotnet-env
        with:
          restore: 'true'

      - name: Build
        run: dotnet build $SLN --no-restore --configuration Release

      - name: Test
        run: dotnet test $SLN --no-build --configuration Release --verbosity normal